version: '3.8'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    image: nginx_image
    restart: always
    depends_on:
        - wordpress
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html/
    networks:
        - inception_net
    
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    image: mariadb_image
    restart: always
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
        - mariadb_db:/var/lib/mysql/
    networks:
        - inception_net

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress/
    image: wordpress_image
    restart: always
    env_file:
      - .env
    ports:
      - 9000:9000
    volumes:
        - wordpress:/var/www/html
    networks:
        - inception_net

  static_website:
    container_name: static_website
    build: ./requirements/bonus/static_website/
    image: static_website_image
    ports:
      - 8080:8080
    networks:
      - inception_net

volumes:
  wordpress:
    driver_opts:
      type: none
      o: bind
      device: /Users/mkarim/Desktop/inception_volumes/wordpress_vol
  mariadb_db:
    driver_opts:
      type: none
      o: bind
      device: /Users/mkarim/Desktop/inception_volumes/mariadb_vol

networks:
  inception_net: 
    driver: bridge