version: '3'

services:
  nginx:
    container_name: nginx_container
    build: ./requirements/nginx/
    image: nginx_image
    ports:
      - 443
    
  mariadb:
    container_name: mariadb_container
    build: ./requirements/mariadb/
    image: mariadb_image
    env_file:
      - .env
    ports:
      - 3306
    
  wordpress:
    container_name: wordpress_container
    build: ./requirements/wordpress/
    image: wordpress_image
    ports:
      - 3306